### 1.내 근태 현황
GET http://localhost:8001/attendance/management/status?searchDate=2024-06-24
Access-Token: Bearer eyJkYXRlIjoxNzIwMDAwMDIwODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDEyMTEwMDEiLCJleHAiOjM2MDAwMTcyMDAwMDAyMH0.XDlx8zfQYD9vhameFeITUUrB8d9OuYzrHA2Hun6dIU3AjuY276f3C0vavIOueyf8Ws6umgwVNIbx_0trDf-XwQ

### 2.내 연차 내역
GET http://localhost:8001/attendance/management/annual_leave_record?startDate=2010-01-01&endDate=2024-07-01
Access-Token: Bearer eyJkYXRlIjoxNzIwMDAwMDIwODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDEyMTEwMDEiLCJleHAiOjM2MDAwMTcyMDAwMDAyMH0.XDlx8zfQYD9vhameFeITUUrB8d9OuYzrHA2Hun6dIU3AjuY276f3C0vavIOueyf8Ws6umgwVNIbx_0trDf-XwQ

### 3.연차 캘린더 조회
GET http://localhost:8001/attendance/management/annual_leave_calendar
Access-Token: Bearer eyJkYXRlIjoxNzIwMDAwMDIwODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDEyMTEwMDEiLCJleHAiOjM2MDAwMTcyMDAwMDAyMH0.XDlx8zfQYD9vhameFeITUUrB8d9OuYzrHA2Hun6dIU3AjuY276f3C0vavIOueyf8Ws6umgwVNIbx_0trDf-XwQ

### 4.내 근태 신청 현황
GET http://localhost:8001/attendance/request_status?startDate=2010-01-01&endDate=2024-07-01
Access-Token: Bearer eyJkYXRlIjoxNzIwMDAwMDIwODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDEyMTEwMDEiLCJleHAiOjM2MDAwMTcyMDAwMDAyMH0.XDlx8zfQYD9vhameFeITUUrB8d9OuYzrHA2Hun6dIU3AjuY276f3C0vavIOueyf8Ws6umgwVNIbx_0trDf-XwQ

### 5.연차 조정 첫페이지
GET http://localhost:8001/attendance/all_leave_record
Access-Token: Bearer eyJkYXRlIjoxNzIwMDAwMDIwODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDEyMTEwMDEiLCJleHAiOjM2MDAwMTcyMDAwMDAyMH0.XDlx8zfQYD9vhameFeITUUrB8d9OuYzrHA2Hun6dIU3AjuY276f3C0vavIOueyf8Ws6umgwVNIbx_0trDf-XwQ

### 6.연차 조정 검색페이지
GET http://localhost:8001/attendance/all_leave_record/search?hireYear=2012
Access-Token: Bearer eyJkYXRlIjoxNzIwMDAwMDIwODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDEyMTEwMDEiLCJleHAiOjM2MDAwMTcyMDAwMDAyMH0.XDlx8zfQYD9vhameFeITUUrB8d9OuYzrHA2Hun6dIU3AjuY276f3C0vavIOueyf8Ws6umgwVNIbx_0trDf-XwQ

