### get 요청 확인
### startDate - 기안일(min) endDate - 기안일(max) templateId - 양식 ID title -
### 제목 draftEmployeeName - 기안자 이름 status - 결재 상태 pageSize - 한 페이지 서류 갯수
GET http://localhost:8001/approval-document?draftEmployeeName=홍&pageSize=10
Content-Type: application/json