### 캘린더 일정 등록
POST http://localhost:8001/schedule/regist
Access-Token: Bearer eyJkYXRlIjoxNzE5Mzc4MDY4Mzg4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDE1MTUwMDMiLCJleHAiOjE3MTkzODE2Njh9.viK_aVWB-SBoM9k4jVheDimHrhx8IGg7ASJFLXqXFwJgC2JkujLSQHYEKrcm7HIEoc1QPcZNFyskviUJPRDpog
Content-Type: application/json

{
  "name": "회의",
  "description": "부장님 아이스 아메리카노",
  "startDate": "2024-06-26",
  "endDate": "2024-06-26",
  "startTime": "09:00",
  "employee": {
    "employeeId": 201511004
  }
}

### 캘린더 일정 조회
GET http://localhost:8001/schedule/detail/1
Access-Token: Bearer eyJkYXRlIjoxNzE5Mzc4MDY4Mzg4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImVtcGxveWVlSWQiOiIyMDE1MTUwMDMiLCJleHAiOjE3MTkzODE2Njh9.viK_aVWB-SBoM9k4jVheDimHrhx8IGg7ASJFLXqXFwJgC2JkujLSQHYEKrcm7HIEoc1QPcZNFyskviUJPRDpog
